### ISSUE TITLE
Use named tuples whenever possible

### ISSUE THREAD

**Issue by vdumoulin** [mila-udem/fuel#125]
One good example of where this would be very useful would be data tuples returned by data streams.

**Comment by dwf** [comment]
+1

**Comment by lamblin** [comment]
I thought named tuples were not picklable. Is that correct?

**Comment by dwf** [comment]
They are picklable.

https://stackoverflow.com/questions/16377215/how-to-pickle-a-namedtuple-instance-correctly

I think you must must must pass the same name that you are assigning to as
the first argument to the namedtuple() class factory, but that's about it.

**Comment by dwf** [comment]
I don't think namedtuples would work with tuples returned by data streams, since you'd need one namedtuple class per conceivable tuple that you could return in order to maintain picklability (and stream transformers can, e.g., add sources). You can't create those classes on the fly because then there'd be nowhere in the source code that the pickle module could reference them.

**Comment by vdumoulin** [comment]
I'll go ahead and close this issue, since this is pretty open-ended.
