### ISSUE TITLE
One billion words. How to find/make the dictionary of tokens

### ISSUE THREAD

**Issue by act65** [mila-udem/fuel#342]
Hey, I am trying to get the builtin dataset -onebillionword - working. However, I am a little mystified as to where to find/get/create a dictionary for the init of the vocabulary.

`from fuel.datasets import OneBillionWord`
`word = OneBillionWord(('training',),[0,1,2,3,4,5],???)`

> vocabulary (dict) – A dictionary mapping tokens to integers. This dictionary is expected to contain the tokens <S>, </S> and <UNK>, representing “start of sentence”, “end of sentence”, and “out-of-vocabulary” (OoV). The latter will be used whenever a token cannot be found in the vocabulary.

Is there one stored somewhere in fuel? Or is there one on the net? or ???

**Comment by chrishokamp** [comment]
you could do something like:

```
from collections import Counter

test_str = 'this this is a test'
words = Counter(test_str.split())
min_freq = 1
vocab = {i[0]:v for v,i in enumerate(words.items()) if i[1] >= min_freq}
vocab_size = len(vocab)
vocab['<S>'] = vocab_size
vocab['</S>'] = vocab_size+1
vocab['<UNK>'] = vocab_size+2
```

Since there are a lot of unique tokens in the billion word corpus, you probably want to use something like `collections.Counter` to filter out tokens below a frequency threshold, or just define a hard cutoff for the number of tokens you want in your vocabulary. So read the billion word corpus into a list of tokens, then count them and discard the tokens below your threshold as in the example above.

**Comment by act65** [comment]
Ok, cool. I think it makes more sense to me (my first time playing around with NLP data). I didnt quite understand what the tokens were for...

Although, I still dont quite get how i would 
> read the billion word corpus into a list of tokens, ...
As first I need a dict of tokens, to read the onebillionwords. 

Although I guess I could go make one, i just thought there would be some more elegant/cleaner way, like;
`
from fuel.datasets import OneBillionWord.English.vocab as vocab
`

Anyway, now i get
`OSError: 1-billion-word/training-monolingual.tokenized.shuffled/news.en-00001-of-00100 not found in Fuel's data path`

I had a quick look for where the data should be, but couldnt find it.

**Comment by chrishokamp** [comment]
Here's a realistic example using the Fuel source code for inspiration -- first you need to [download the 1-billion-word corpus](http://www.statmt.org/lm-benchmark/), untar it, rename the inner directory to `1-billion-word`, and put it in your $FUEL_DATA_PATH (note that I found the renaming thing by reading [this code](https://github.com/mila-udem/fuel/blob/master/fuel/datasets/billion.py#L49-L52)). 

```
import codecs
import os
from collections import Counter

from fuel.utils import find_in_data_path

which_partitions = range(1,5)
files = [find_in_data_path(os.path.join(
         '1-billion-word', 'training-monolingual.tokenized.shuffled',
         'news.en-{:05d}-of-00100'.format(partition)))
         for partition in which_partitions]

words = Counter()

for f in files:
    with codecs.open(f, encoding='utf8') as inp:
        lines = [l.split() for l in inp.read().strip().split('\n')]
        words.update(word for line in lines for word in line)
        
min_freq = 10
vocab = {i[0]:v for v,i in enumerate(words.items()) if i[1] >= min_freq}
vocab_size = len(vocab)
vocab['<S>'] = vocab_size
vocab['</S>'] = vocab_size+1
vocab['<UNK>'] = vocab_size+2
```

A few caveats -- 
- the billion word dataset is huge, so I'm just loading the first 4 partitions in this example. That should give you a good idea of the most frequent tokens anyway. You could definitely run out of RAM as the size of your `Counter` grows. 
- the TextFile dataset in Fuel depends upon the input files being whitespace tokenized -- for the billion words dataset this is already the case, but for other data you would need to make sure that the files are tokenized properly.
- usually for model development it's easier to know the exact size of the vocab, instead of thresholding based on frequency, if you want to do that you could replace 
```
    vocab = {i[0]:v for v,i in enumerate(words.items()) if i[1] >= min_freq}   
```
with:
``` 
    vocab = {i[0]:v for v,i in enumerate(words.most_common()[:50000])}    
```
Your final vocab size would then be 50000+3 (because we added the unknown, begin and end tokens).
- I usually do this preprocessing once, then use `cPickle` to save the vocab dict somewhere, then load the pickled dict later. Otherwise, every time you run your code you'll have to wait for the vocab to build, which will get boring :smile: 

BTW I'm not a fuel developer but I suspect it would be better for you to ask this kind of question on the [mailing list](https://groups.google.com/forum/#!forum/fuel-users), since issues are typically for things related to development, like bugs and proposed features.

**Comment by act65** [comment]
Ok, thanks. I'll have a deeper look into it in a couple of days, have a few other things on atm.

And yea, I get that. I'll close the issue and ask these questions somewhere else. (still new to all this stuff).

Anyway, thanks a lot for the help chris.
