### ISSUE TITLE
Indexable Assumes Data is Available in Constructor

### ISSUE THREAD

**Issue by rizar** [mila-udem/fuel#39]
Currently `Indexable` requires data to be passed as a constructor argument. I do not find it nice, because some questions about the dataset can be answered even before actually loading the data. See https://groups.google.com/forum/#!topic/blocks-users/Bh9HtqmXjJk, for instance.

**Comment by bartvm** [comment]
I don't fully agree. The length of an indexable object is only available if you hardcode it. This was what was done for MNIST in the past; the constructor had the number of examples hardcoded into it, and then postponed loading the actual data until later.

By relying on a superclass that simply expects data to be indexable we can factor out a lot of logic, and keep loading things like MNIST clean and simple. To re-introduce the behaviour you want we would need to introduce an entirely new class for datasets for which we hardcode a bunch of metadata. I wasn't too much of a fan of the postponed data loading in the first place, because I thought it was counter-intuitive that the main loop slows down, loading the data, long after you've constructed an MNIST object.

**Comment by rizar** [comment]
> The length of an indexable object is only available if you hardcode it.

Exactly and I would even encourage people to do it. I think that this is a sort of metadata that should be acquirable before loading.  

Also I find it inconsistent that an unpickled dataset does not contain data, whereas a created does. 

> By relying on a superclass that simply expects data to be indexable we can factor out a lot of logic, and keep loading things like MNIST clean and simple. 

I fully agree that `Indexable` is a useful superclass. But there is no need to have 

```python
       if isinstance(indexables, dict):
            self.indexables = [indexables[source][start:stop]
                               for source in self.sources]
            if not all(len(indexable) == len(self.indexables[0])
                       for indexable in self.indexables):
                raise ValueError("sources have different lengths")
        else:
            self.indexables = [indexables]
```

in constructor when you already have it in `load`, even though this `load` is currently copy-pasted in every descendant. 

> because I thought it was counter-intuitive that the main loop slows down, loading the data, long after you've constructed an MNIST object.

Good point. But we can have `MainLoop` explicitly trigger the loading procedure at the initialization stage.

So I propose the following refactoring:

```
class Indexable(Dataset):

    def __init__(self, indexables=None, provides_sources=None, num_examples=None, **kwargs):
    """If indexables are given, calls _install, if not, simply set `provides_sources` and 
    `num_examples`.
    """
  
    def _install(self):
    """Move here all logic from constructor."""
        ...

    def _load(self):
    """Loads the array of indexables, to be overriden in descendants."""
        pass
   
    def load(self):
    """The one called by `do_not_pickle_attributes`."""
        self._install(self._load())

```    

The subclass will have `provides_sources` and `num_examples` hardcoded in the constructor and will have to implement the `_load` method.

**Comment by bartvm** [comment]
I'm not a fan. First of all, the `_load` methods shouldn't be part of `IndexableDataset`. They are only used by datasets which actually need to read from disk, which has nothing to do with being indexable. How are you planning on supporting something like `IndexableDataset(indexables=range(10))` now? If I don't subclass I can't override `_install`.

The behavior of only loading data in the main loop was a quirk IMHO, and one I'm happy to get rid of. I see no point in all this complex behavior such postponing loading data, using 4 (!) different methods to do so, etc. just so that we can get `num_examples` for one particular subset of datasets (`provides_sources` can just be set as a class attribute).

Given the discussion at https://github.com/laurent-dinh/fuel/commit/08a7ec7727c6f50d7bfffc69a486a91fbdd4b31d#commitcomment-10017392, this would become even less relevant. If we rely on HDF5, we can easily retrieve the shape without hardcoding or loading anything, and without having a complicated 4-step constructor in a class that should just handle `IndexableDataset(indexables=*data here*)`.

**Comment by rizar** [comment]
You can move both `_load` and `load` to a subclass which assumes that data is loaded and this will not change the big picture. The main thing is to separate `_install` which requires `indexables` and `__init__` that does not. That is 2-step constructor, not 4-step.

> How are you planning on supporting something like IndexableDataset(indexables=range(10)) now?

Easy: `__init__` calls install.

>  using 4 (!) different methods

Right now 3 are used, from which the third one is copy-pasted all over.

I will have to read the discussion first to give any comments.

**Comment by vdumoulin** [comment]
@rizar is this issue still relevant?

**Comment by rizar** [comment]
I guess no, because `H5PyDataset` serves users with big datasets now.
